# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/e9d246f1-d50c-421d-8381-ac6894bc3872";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/7CF1-4BBD";
      fsType = "vfat";
    };

  fileSystems."/mnt/hdd" =
    {
      device = "/dev/disk/by-uuid/EE18BC2218BBE82B";
      fsType = "auto";
      options = [ "nosuid" "nodev" "nofail" "x-gvfs-show" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/19ed36cd-999f-4147-8d92-e1f653d0b655"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # high-resolution display - requested to disable when switching to unstable from 21.11
  hardware.video.hidpi.enable = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = "performance";

  # https://github.dev/Kranzes/nix-config
  hardware = {
    enableAllFirmware = true;
    enableRedistributableFirmware = true;
    cpu.amd.updateMicrocode = true;
  };
}
